version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 7
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 100
  method-lines:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 1000
exclude_patterns:
- "**/mock/"
- "**/test/"
- "**/Test.java"
