site_name: Cloudbreak Deployer
site_url: http://sequenceiq.com/cloudbreak-deployer
theme: mkdocs
theme_dir: mkdocs_theme
dev_addr: 0.0.0.0:8000
pages:
    - 'Home': index.md
    - 'Docs':
        - Architecture : architecture.md
        - Configuration : configuration.md
        - Database : database.md
        - Development : development.md
        - Changelog : changelog.md
