site_name: Cloudbreak Deployer
site_url: http://sequenceiq.com/cloudbreak-deployer
theme: mkdocs
theme_dir: mkdocs_theme
dev_addr: 0.0.0.0:8000
pages:
    - 'Home': index.md
    - 'Docs':
        - AWS : aws.md
        - Azure : azure.md
        - GCP : gco.md
        - OpenStack : openstack.md
        - Shell : shell.md
        - Recipes: recipes.md
        - Kerberos: kerberos.md
