auth:
  license:
    file: license.txt
  config:
    dir: /etc/auth
  databus:
    credential:
      tp:
        file: altus_credentials
      fluent:
        file: databus_credentials
  mock:
    ccm.enable: false
    event-generation:
      expiration-minutes: 10