environment:
  experience:
    liftie:
      workloads:
      pathInfix: /liftie/api/v1
      address: https://${MOCK_INFRASTRUCTURE_HOST:localhost}:${MOCK_INFRASTRUCTURE_BIND_PORT:10090}
      policyPath: /prerequisites?cloudPlatform={cloudProvider}
    path:
      componentToReplace: "{environmentCrn}"
      toReplace:
        envCrn: "{environmentCrn}"
        cloudProvider: "{cloudProvider}"
    configs:
      - name: MLX
        description: Data Warehouse Clusters
        businessName: Data Warehouses
        environmentEndpointPort: ${MOCK_INFRASTRUCTURE_BIND_PORT:8080}
        baseAddress: http://${MOCK_INFRASTRUCTURE_HOST:localhost}
        address: http://${MOCK_INFRASTRUCTURE_HOST:localhost}:${MOCK_INFRASTRUCTURE_BIND_PORT:8080}
        internalEnvironmentEndpoint: /ml/environment/{environmentCrn}
        policyPort: ${MOCK_INFRASTRUCTURE_BIND_PORT:8080}
        policyEndpoint: /prerequisites?cloudPlatform={cloudProvider}
        forceDeleteCapable: true
